version: "3.7"

services:
  web-game-db:
    container_name: web-game-db
    image: mongo
    
  web-game-server:
    container_name: web-game-server
    external_links:
      - web-game-db
    depends_on:
      - web-game-db
